version: '2'

services:
  selenium:
    # image: selenium/standalone-chrome:110.0
    image: selenium/standalone-firefox:109.0-geckodriver-0.32
    container_name: standalone-firefox
    environment:
    - SE_NODE_MAX_SESSIONS=2
    - SE_NODE_SESSION_TIMEOUT=40
    ports:
    - 4444:4444
    # shm_size: '1gb'
    # volumes:
    # - /dev/shm:/dev/shm
    # restart: always

  coductcrawler:
    build: 
      context: ${CRAWLER_PATH:-.}
    command: sh -c "python3 app.py"
    image: myappcrawler.azurecr.io/crawler
    domainname: "coductCrawlerCompose"
    container_name: crawler-api
    volumes:
    - ${CRAWLER_PATH:-.}/app:/app
    ports:
    - 4000:4000
    depends_on:
    - selenium
    # restart: always
    environment:
    - ACCESS_TOKEN=${ACCESS_TOKEN:-default}
    - WAITING_TIME=${WAITING_TIME:-5}
    - SELENIUM_HUB=${SELENIUM_HUB:-http://selenium:4444}