version: '2'

services:
  # selenium:
  #   image: selenium/standalone-firefox
  #   ports:
  #   - 4444:4444
  #   restart: always

  app:
    build: 
      context: ${CRAWLER_PATH:-.}
    command: sh -c "python3 app.py"
    image: mycrawlercontainer.azurecr.io/crawler
    domainname: "coductCrawler"
    volumes:
    - ${CRAWLER_PATH:-.}/app:/app
    ports:
    - 4000:4000
    # depends_on:
    # - selenium
    restart: always
    environment:
    - ACCESS_TOKEN=${ACCESS_TOKEN:-default}