version: '2'

services:
  selenium:
    image: selenium/standalone-firefox
    ports:
    - 4444:4444
    restart: always

  app:
    build: 
      context: .
    command: sh -c "python3 app.py"
    volumes:
    - ./app:/app
    ports:
    - 4000:4000
    depends_on:
    - selenium