on:   
  push:
    branches:    
      - main
name: update container registry

env:
  RESOURCE_GROUP: PowerApps
  REGISTRY_NAME: myappcrawler
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Build and push image
      run: |
        az acr login -n $REGISTRY_NAME -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
        az acr build --file Dockerfile --registry $REGISTRY_NAME -t crawler:${{ github.sha }} -t crawler:latest .

    ### In case you want to launch container instance with last version of image
    # https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-github-actions?tabs=userlevel
    - name: 'Run Azure CLI commands'
      run: |
        az deployment group create --resource-group $RESOURCE_GROUP --template-file azuredeploy.json
