on: [push]
name: ACI

jobs:
    build:
        runs-on: ubuntu-latest
        environment: development
        steps:
        
        - name: Install Docker Compose CLI 
          run: curl --max-time 5 --retry 5 --retry-delay 0 -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh

        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            
        - name: Log into Azure
          run: |
            docker login azure --client-id ${{ secrets.AZURE_CLIENT_ID }} --tenant-id ${{ secrets.AZURE_TENANT_ID }} --client-secret ${{ secrets.AZURE_CLIENT_SECRET }} 
            az acr login -n myappcrawler -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }} 
            
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/crawler:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/crawler:${{ github.sha }}
